### ISSUE TITLE
Command "shield:setup" not found.

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#246]
I installed the `v1.0.0-beta` just like the docs explained, and tried to run the command: `php spark shield:setup` but it returned an error that the command doesn't exist.

Further checks showed that the "Commands" directory was not included when it was installed via composer and the folder also does not exist in the master branch, but exist in the develop branch.

Is this an intentional behaviour ? Should we stick to the `dev-develop` flag for installation if we need to run commands ?

**Comment by datamweb** [comment]
Hi @sammyskills , Command `shield:setup` was developed after the release of version `v1.0.0-beta`.
So it **does not exist** in version `v1.0.0-beta`.
To use it you have to use branch `develop`.

**Thanks**

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/shield/blob/develop/docs/0%20-%20install.md#important-composer-error

**Comment by sammyskills** [comment]
Then I think the doc is a bit misleading. It states the different ways of getting shield installed, but doesn't indicate the option that can work with commands.

Also, which version would you advise to be used in production: `v1.0.0-beta` or `develop` ?

**Comment by kenjis** [comment]
It might be misleading, but it is GitHub's specification.

https://github.com/codeigniter4/shield/blob/develop/docs/0%20-%20install.md
This is the docs for `develop` branch. See the URL has `shield/blob/develop/`.

If you need to read `v1.0.0-beta` docs, you need to specify `v1.0.0-beta` tag.
https://github.com/codeigniter4/shield/blob/v1.0.0-beta/docs/0%20-%20install.md

> Also, which version would you advise to be used in production: v1.0.0-beta or develop ?

In production both are not recommended.
Because `v1.0.0-beta`  is beta release, and `develop` is development branch.
v1.0.0 and after would be recommended.

**Comment by sammyskills** [comment]
Thanks @kenjis for the clarification.
