### ISSUE TITLE
Error after Register

### ISSUE THREAD

**Issue by sanjeevdivekar** [codeigniter4/shield#292]
Hello,

I am getting the following error after registration

Call to undefined function CodeIgniter\Shield\Controllers\auth()

I am a newbie to CodeIgniter and I am using the dev-develop version of codeigniter4/shield

![Screenshot from 2022-07-09 17-39-17](https://user-images.githubusercontent.com/1086717/178105137-499affc9-a622-474e-9172-f7f3ca392a29.png)

Regards,

**Comment by datamweb** [comment]
Hello @sanjeevdivekar , welcome to **shield**.

This problem is related to **not adding**  
```php
 $this->helpers = array_merge($this->helpers, ['auth', 'setting']);
``` 
to file `app\Controllers\BaseController.php`.

Please run the following command to fix this problem:
```
> php spark shield:setup
```
For more info see [installation](https://github.com/codeigniter4/shield/blob/develop/docs/install.md#installation
)
Also, if possible, from now on, please register your questions in [this section](https://github.com/codeigniter4/shield/discussions/categories/q-a).

**Thank you!**

**Comment by sanjeevdivekar** [comment]
Thank you very much @datamweb for your quick response.

My Problem is solved
