### ISSUE TITLE
Handler or Authenticator ?

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#67]
In docs and in the namespace, `Handler` is used.
https://github.com/lonnieezell/codeigniter-shield/blob/develop/docs/2%20-%20authentication.md#available-handlers
https://github.com/lonnieezell/codeigniter-shield/tree/develop/src/Authentication/Handlers

But the interface name uses `Authenticator`.
https://github.com/lonnieezell/codeigniter-shield/blob/develop/src/Authentication/AuthenticatorInterface.php

If these terms refer to the same thing, they should be unified.

**Comment by lonnieezell** [comment]
I don't really have an issue changing that. To explain, though - the interface is for a class that Authenticates. In CodeIgniter 4 we call the different "drivers" for a solution Handler, which is why they were called that. I still think there's logic having different names but don't really care if everyone else wants to change that.

**Comment by kenjis** [comment]
It seems there are two things.

1. *Authenticator*: a class that authenticates.
2. *Authenticator alias*: string name (alias) for an Authenticator (object).

I don't think we need to use the word "handler".

**Comment by lonnieezell** [comment]
I'm ok with this change.
