### ISSUE TITLE
What behavior do you expect from save($user)?

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#69]
The `UserProvider::save()` method saves a User entity.
https://github.com/lonnieezell/codeigniter-shield/blob/9301131ca8c1408e537fcb22de191b8eaa431dad/src/Interfaces/UserProvider.php#L28-L35

The User entity has Identities. When you save the User, should the Identities also be saved or not?

**Comment by lonnieezell** [comment]
I don't think saving identities makes sense here. We don't have any utility methods for adding an identity to a user, other the email identity and that writes to the database immediately. So currently everything is working through the UserIdentityModel, so I don't see a need to deal with it here.

**Comment by MGatner** [comment]
I also chose to drop this from my meta-package: https://github.com/tattersoftware/codeigniter4-users/blob/develop/src/UserFactory.php

**Comment by kenjis** [comment]
https://github.com/lonnieezell/codeigniter-shield/blob/c38c3741ed0dd24b7d86021f52890b3a90bff5a8/src/Authentication/Handlers/Session.php#L134-L137
The password_hash seems to be not saved in the database.

**Comment by kenjis** [comment]
To begin with, this library provides authentication and authorization. Do we need an interface to save users?

**Comment by MGatner** [comment]
It's a valid question. I think I brought this up earlier but this library is currently fulfilling two "functions": authentication/authorization interfacing and scaffolding, and a fulfillment of the same. I think it would be a fine solution to divide these into two separate libraries: one for the interfaces and any Auth functions you can do *only with those interfaces*, and another that implements the former with a model, entity, controller, etc. But as long as these two remain bundled together I think we need to fulfill our own interfaces in "traditional" CodeIgniter fashion, which means including a full-fledged UserModel with saving capabilities (maybe even a basic REST Controller for Users??)

**Comment by lonnieezell** [comment]
> The password_hash seems to be not saved in the database.

Good catch. Seems that didn't get changed after I switched to using identities. 

I honestly don't know that an interface for saving users would be all that beneficial. I think it might be more helpful to include a UserModel `beforeInsert`/`beforeUpdate` event function that a) checks if they have a password and creates the password_hash on the entity and then b) if they have a password_hash - update the correct identity. 

>  in "traditional" CodeIgniter fashion, which means including a full-fledged UserModel with saving capabilities (maybe even a basic REST Controller for Users??)

What else do you think the UserModel is missing other than handling of passwords better? And for the record - I think a REST controller is likely out of scope, especially since CI doesn't have a standard way of transforming a record into a JSON representation (something I'd like to fix down the road).

**Comment by MGatner** [comment]
> since CI doesn't have a standard way of transforming a record into a JSON representation

What's wrong with `ResponseTrait::respond()`?

**Comment by lonnieezell** [comment]
That creates a JSON instance of the record, but doesn't allow you to tell it _how_ the record should look, which relationships to include, etc. I was thinking along the lines oh The PHP League's Fractal, or Laravel Resources.

**Comment by MGatner** [comment]
I'm intrigued. We should talk more. In Rails `respond json: user` will cast the parameter to an array and JSONify it - it is up to the "model" (our `Entity`) to determine what all gets included in the "to array" cast. Our situation is a little trickier since we rely on `__toArray()` for pre-database processing - but I think the general shape of this approach is pretty good.

But I will look at those alternatives at some point to see how they handle this.

**Comment by kenjis** [comment]
> I think it would be a fine solution to divide these into two separate libraries: one for the interfaces and any Auth functions you can do only with those interfaces, and another that implements the former with a model, entity, controller, etc. 

I think we need to separate the two in this library.
Otherwise, the interfaces will not be complete. I mean we can't fix PHPStan errors.

**Comment by kenjis** [comment]
> I think it might be more helpful to include a UserModel beforeInsert/beforeUpdate event function that a) checks if they have a password and creates the password_hash on the entity and then b) if they have a password_hash - update the correct identity.

You think developers who use the User object should not have to be aware that there is an Identity object in the User.
and saving the User object automatically saves the Identities is better.

**Comment by MGatner** [comment]
@lonnieezell or @lonnie-vault how much do you hate the idea of splitting this up? I even think the interfaces and service could go in the main framework repo (`CodeIgniter\Auth`) and then this repo could remain as the implementing classes.

**Comment by lonnieezell** [comment]
I believe we've decided against splitting for now, so I think we can close this? I'll open a new issue with the needed before/after insert/update methods to handle password hash saving. 

Feel free to re-open if needed. Just trying to keep things cleaned up and moving as much as possible.
