### ISSUE TITLE
User Entity is too big?

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#95]
Here is the public method list. Are so many methods really necessary?

```
__construct
__get
__isset
__set
__unset
accessTokens
addGroup
addPermission
can
cast
createEmailIdentity
currentAccessToken
fill
generateAccessToken
getAccessToken
getAccessTokenById
getAuthEmail
getAuthEmailColumn
getAuthId
getAuthIdColumn
getAuthPassword
getEmail
getEmailIdentity
getGroups
getIdentities
getIdentity
getPassword
getPasswordHash
getPermissions
getRememberColumn
getRememberToken
hasChanged
hasPermission
identitiesOfType
inGroup
jsonSerialize
lastLogin
removeGroup
removePermission
revokeAccessToken
revokeAllAccessTokens
setAccessToken
setAttributes
setEmail
setPassword
setRememberToken
syncGroups
syncOriginal
syncPermissions
toArray
tokenCan
tokenCant
toRawArray
touchIdentity
```

**Comment by MGatner** [comment]
To be fair you've included `Entity` methods as well. They definitely contribute to the problem but this is a framework pattern we are working with and should be partially addressed with the `Entity` class elsewhere. "Composition over inheritance" suggests we could deal with it here, but we would have to disassociate from `Model` as well since it generates the entities. 

A lot of the other methods would be solved by my proposal to embrace more in our interface, since we could guarantee baseline property handling.

**Comment by lonnieezell** [comment]
For usability, yes, I think they need to be there. This allows you to have a user instance and run your auth checks directly on that user instead of needing to use an external library for all of the checks, and these are all things that operate on a single user. 

In other words, 

```
if ($user->inGroup('beta') { 
    //
}
```

versus

```
if (service('groups')->userInGroup($user, 'beta') {
    //
}
```

While the second option still works I believe the first provides a better developer experience and less mental overhead.
