### ISSUE TITLE
Replace bool returns

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/shield#96]
Methods that return a `bool` to indicate "success/failure" should be refactored to `void` and throw a meaningful exception(s) instead. See in particular the interface methods.

**Comment by lonnieezell** [comment]
Can I ask why? Is this a current best practice I'm not aware? To me a boolean value is simpler to handle, reads better in code and reflects the success state just fine.

**Comment by MGatner** [comment]
I can't actually find a reference so I'm not sure where I learned this, but AFAIK it is an OOP vs procedural thing. Class action methods are assumed to do the thing they do so shouldn't need a "true" value, so false only becomes meaningful as a "failure" state; but we have a whole language construct devoted to failing!

Maybe I'm wrong about that practice, but even so I prefer exceptions for two other reasons:
1. They allow for multiple failure distinctions - same method could throw `InvalidArgumentException` and `RuntimeException`, and some calling scenarios may want to handle these different (or not at all).
2. They can convey meaning - not only via the class name, but you get to add a reason which can percolate to something helpful for either the developer or end user. Otherwise you are trying to return `false` and then store some reason strings that are hard to pass around, it gets to be messy.

**Comment by MGatner** [comment]
I would also point out that things currently aren't very consistent; take for example `login()` which *both* throws and returns `bool`: https://github.com/codeigniter4/shield/blob/b779e554073712a69027da09b8939ff874db30f9/src/Authentication/Authenticators/Session.php#L166-L178

And then the very next method calls `login()` but returns `void`: https://github.com/codeigniter4/shield/blob/b779e554073712a69027da09b8939ff874db30f9/src/Authentication/Authenticators/Session.php#L214-L228

And some methods have no logic that could even return `false`: https://github.com/codeigniter4/shield/blob/b779e554073712a69027da09b8939ff874db30f9/src/Authentication/Authenticators/AccessTokens.php#L180-L190

**Comment by kenjis** [comment]
I propose to introduce two library-specific base exceptions.
- RuntimeException extends \RuntimeException
- LogicException extends \LogicException

**Comment by kenjis** [comment]
> PHP itself is fairly lax with this, and a call to file_get_contents() will usually just get you a FALSE and a warning. Many older PHP frameworks like CodeIgniter will just return a false, log a message to their proprietary logs and maybe let you use a method like $this->upload->get_error() to see what went wrong. The problem here is that you have to go looking for a mistake and check the docs to see what the error method is for this class, instead of having it made extremely obvious.
https://phptherightway.com/#exceptions

**Comment by lonnieezell** [comment]
> It is also said "Use Exceptions for Exceptional Problems".

That's what I was taught coming up through the ranks, and basic success/failure wasn't enough to warrant an exceptional issue. If tides are changing then I suppose that's one thing. The PHP The Right Way article didn't give much advice on when to use them, unfortunately, just stating that Ruby on Rails uses them for everything and CodeIgniter didn't use them enough. 

Sure - I might have some inconsistencies in return values. Not surprising considering how it was developed (in chunks often weeks or months apart from each other). And a logic pass over that wouldn't hurt. 

In something like the `login` method you called out, it returns bool because it returns the trigger results, which might not be necessary. But I can see logical reasons for using both: it returns boolean for whether or not it was able to accomplish its task, assuming that the reason for failure was a "normal failure" - or one that could be expected under normal circumstances. But then if there was something bigger that it had no way of working with (file can't be found, missing driver, etc) then an exception would be thrown so that `exceptional problem` can be dealt with. 

I'm not sold that all boolean results should be replaced with exceptions, personally.

**Comment by MGatner** [comment]
Understood! This is a good conversation, I didn't realize how much of this was my own opinion instead of generally accepted / best practice. I still prefer using exceptions but I won't impose that on other libraries.

**Comment by kenjis** [comment]
Inconsistency in Authenticator interface still remains.
