### ISSUE TITLE
Emailer Helper

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/shield#97]
The `emailer()` function makes me nervous. I would suggest removing it, or moving it to a separate package, or marking it `@internal` if it is really necessary. I'm not sure when this library hopes to release but if it is after CodeIgniter 4.2 we can probably find a way to accomplish this with `Mailed` instead.

**Comment by lonnieezell** [comment]
I think it will release before 4.2. Even so, though, I think it should stay and would actually be beneficial for a couple of reasons: 

1. It allows the config settings to be retrieved from the database through the `setting` helper, which core doesn't do (and is a huge benefit for apps developing on top of it)
2. Any app using this is shielded from the upcoming mail change to some extent since the details are taken care of for them.

**Comment by MGatner** [comment]
Any opposition to marking it `@internal`? This at least gives us the flexibility to update it to use `Mailer` and maybe change the definition as these things come down the pipe. I do think it is terrible helpful, I just don't want us to get locked into a completely-unrelated component. 

I also am still keen on a "Settings Registrar" that will help automate some of this, so we don't need to meddle in service processes just to interpose our database configurations.

**Comment by kenjis** [comment]
Marking it `@internal` would be better.
We could move/remove it later.

**Comment by lonnieezell** [comment]
`@internal` works for me.
